Description: >
  Shola Akanni Bluefish / Udalearn
  This deploys a VPC

Resources:
  FirstEc2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-063dd30adbb186909
      Tags:
      - Key: name
        Value: myfirsttestec2
      - Key: Type
        Value: Test Instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref newlyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '*'
          ToPort: '*'
          CidrIp: 41.203.115.33/32
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: '*'
          ToPort: '*'
          CidrIp: 41.203.115.33/32

  VPCcreate:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
  #      - Key: stack
  #        Value: production
        - Key: name
          Value: newlyVPC