Description: >
  Shola Akanni Bluefish / Udalearn
  This deploys a VPC

Resources:
  FirstEc2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0cff7528ff583bf9a
      Tags:
      - Key: name
        Value: myfirsttestec2
      - Key: Type
        Value: Test Instance
      NetworkInterfaces:
        AssociatePublicIpAddress: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref newlyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: '*'
          ToPort: '*'
          CidrIp: 0.0.0.0/0

  VPCcreate:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
  #      - Key: stack
  #        Value: production
        - Key: name
          Value: newlyVPC


          #vpc-0f57b07aa611a483d

  VPCcreate:
    Type: AWS::EC2::
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
  #      - Key: stack
  #        Value: production
        - Key: name
          Value: newlyVPC          
          